name: Survivor
version: 0.1
main: net.neferett.Survivor.Survivor
author: Neferett
depend: [BukkitAPI, GameAPI, BossBarAPI]
commands:
  survivor:
    usage: /<command> <args>
    description: Survivor settings
